### ISSUE TITLE
Update by multi-thread

### ISSUE THREAD

**Issue by vicfaith** [j256/ormlite-android#16]
Hi all,

I came across a weird issue while updating a table by multi threads.
Each thread fetches data from web service and create/update it into the table - callBatchTasks is used.
if 2 or 3 threads update rows (around 50), no problem. if 14 threads update total 200 rows simultaneously, sometimes, in a random way, some rows are deleted. I found there is no delete api explicitly.

db before
1 a
2 b
3 c
4 d
5 f

db after
1 a
2 b
5 f

the createOrUpdate api returns successful for all 5 rows but where are 2 rows?
I'm not sure if I miss something or this is a bug? Thanks in advance.

Thanks,
Daniel

**Comment by j256** [comment]
Sorry for the delay.  Can you write a junit test that reproduces this?  We are getting ready to [finally] push 4.49 and I'd like to make sure this isn't an issue.

**Comment by j256** [comment]
Ok, I understand this now and it makes sense.  Multiple threads cannot use the `callBatchTasks(...)` at the same time because there is a single database connection and the transactions are getting screwed up.  I just added the following to the javadocs:

NOTE: Depending on your underlying database implementation and whether or not you are working with a single database connection, you may need to synchronize around calls to this method otherwise the database transactions that are used may clash when called simultaneously from multiple threads. You may also need to synchronize other calls to transactions and `dao.setAutoCommit(...)`.

**Comment by j256** [comment]
Related to https://github.com/j256/ormlite-android/issues/34
