### ISSUE TITLE
CursorLoader and Support Library

### ISSUE THREAD

**Issue by dnlbauer** [j256/ormlite-android#31]
Hey,

Once there were support versions for apptools.OrmLiteCursorAdapter and apptools.OrmLiteCursorLoader located in apptools.support but they seem to have been removed. Whats the reason for this?

This makes it really hard to implement CursorAdapters below Api v11 without fiddling around cursors.

**Comment by j256** [comment]
It this needed @danijoo ?  I removed them by accident a while back.

**Comment by danijoo** [comment]
I worked arround this for now, but I think they shouldnt be removed. A lot of people use support fragments because of their compatibility to ViewPager and stuff like that. Inside that fragments, only the SupportLoaderManager is available, which does not work together with OrmListeCursorLoader (non-support version)
